;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Necro_Tags",DevComment="Tags que se usaran en el juego, es recomendadle usar tags a referencias a objetos, son FName facil de comparar.")
+GameplayTagList=(Tag="Necro_Tags.Mision01",DevComment="")
+GameplayTagList=(Tag="Necro_Tags.Mision02",DevComment="")
+GameplayTagList=(Tag="Necro_Tags.Mision01.Antorcha",DevComment="La antorcha a encender")
+GameplayTagList=(Tag="Necro_Tags.Mision01.Bencina",DevComment="")
+GameplayTagList=(Tag="Necro_Tags.Mision01.Cementerio",DevComment="")
+GameplayTagList=(Tag="Necro_Tags.Mision01.Enemy",DevComment="saqueadores de tumbas")
+GameplayTagList=(Tag="Necro_Tags.Mision02.EnemigosBosque",DevComment="")
+GameplayTagList=(Tag="Necro_Tags.Npc",DevComment="")
+GameplayTagList=(Tag="Necro_Tags.Npc.Guardian",DevComment="")
+GameplayTagList=(Tag="Necro_Tags.Npc.ViejoSabio",DevComment="")

